toolbar:
  - styleselect | bold italic | undo redo | image | media | link | code
plugins:
  - image
  - link
  - media
  - code
extended_valid_elements: 'script, script[charset|defer|async|language|src|type]'
